apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: amazon-ssm-agent
  name: amazon-ssm-agent
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: amazon-ssm-agent
  template:
    metadata:
      labels:
        app: amazon-ssm-agent
    spec:
      containers:
      - name: amazon-ssm-agent
        image: ghcr.io/jnig/amazon-ssm-agent-docker:main@sha256:fe1fb3b1befa3f5c22847b88a1abb92d884fec0a207ed2c592b511ae86fed780
        env:
        - name: SSM_ID
          valueFrom:
            secretKeyRef:
              name: amazon-ssm-agent
              key: ssm_id
        - name: SSM_CODE
          valueFrom:
            secretKeyRef:
              name: amazon-ssm-agent
              key: ssm_code
        - name: SSM_REGION
          value: "eu-central-1"
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
        volumeMounts:
        - mountPath: /host
          name: host
        - mountPath: /var/lib/amazon/ssm/
          name: ssm
      hostPID: true
      hostNetwork: true
      tolerations:
      - effect: NoSchedule
        operator: Exists
      volumes:
      - hostPath:
          path: /
        name: host
      - hostPath:
          path: /opt/amazon-ssm-agent
        name: ssm
